# Generated by Django 5.2.1 on 2025-05-20 10:40

import appdemo.models.container
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appdemo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "chunks_json",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[appdemo.models.container.chunks_validator],
                    ),
                ),
                ("vector_binary", models.BinaryField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appdemo.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "chunks_json",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[appdemo.models.container.chunks_validator],
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appdemo.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
